### ISSUE TITLE
Sound is off

### ISSUE THREAD

**Issue by cornellouis** [budude2/openfpga-GBC#33]
In super Mario land 2 when pressing “a” to enter a level, the last note of the sound effect is off.  Maybe too low frequency?  Definitely different from spiritualized core and real hardware.

**Comment by Yasaka7** [comment]
Can confirm something is weird there. i noticed it in pokemon romhacks and zelda oracle of seasons where there are some cracks on certain sounds which doesnt occure on the spiritualized core.

**Comment by Turbochop** [comment]
Can also confirm. Issue can be heard even in the Game Boy bios sound. Most prominent in the second note.

**Comment by budude2** [comment]
This should be fixed in release V1.2.3 https://github.com/budude2/openfpga-GBC/releases/tag/v1.2.3
