### ISSUE TITLE
v1.0.6 Totally Broke Analogue Pocket Screen Filters

### ISSUE THREAD

**Issue by 825i** [budude2/openfpga-GBC#35]
With v1.0.6 none of the updated screen filters work at all. If I press the shortcut key combination to toggle through them, nothing happens. I get a tiny little partially opaque line that appears briefly at the bottom of my screen. So something "tried" to happen but that was it.

The screen filter is stuck on the one I selected before I updated. Currently GB-SP 101.

I am also using Analogue Pocket firmware **v2.1**

**Comment by SaulGoodman1337** [comment]
same here

**Comment by Dawbo66** [comment]
After updating I always use option 7 on Matt's updater, may work for you, as it did for me.

**Comment by Dawbo66** [comment]
Use matt pannella updater as I don't know if the other updaters have the add screen filters option, I always use this after an update for any core. Option 7 for screen filters, the cores my side all work with filters, so may be delete yours , then update them, then add screen filters.

**Comment by Dawbo66** [comment]
I don't use pocket sync, but would say I have no issues with the filters, I would update with another updater.

**Comment by Dawbo66** [comment]
> > I don't use pocket sync, but would say I have no issues with the filters, I would update with another updater.
> 
> What would you recommend? I've had no problems with Pocket Sync over the last few months.

https://github.com/mattpannella/pupdate
use option 7 for filters, I do this every time I update.
