### ISSUE TITLE
Fast-Forward does not work 

### ISSUE THREAD

**Issue by DunhamGitHub** [budude2/openfpga-GBC#43]
FF does not work with 1.0.8.

I did also (to no avail):
- Reset core
- Reset controls

<img width="489" alt="Screenshot 2024-02-27 at 18 29 19" src="https://github.com/budude2/openfgpa-GBC/assets/6884752/7572c88f-aefd-4020-b39c-5035309a80f6">

**Comment by Dawbo66** [comment]
just checked the 2 cores on mine are both working as they should, but that's with default shoulder button..

**Comment by DunhamGitHub** [comment]
> just checked the 2 cores on mine are both working as they should, but that's with default shoulder button..

I again reset everything (FF now set to shoulder buttons) -> does NOT work on my APocket (holding or quick toggling does not go to FF)

_Test cases: digital Roms or Link's Awakening and Pokemon Red DX_

* Previous version of this Core does properly toggle FF

**Comment by Dawbo66** [comment]
I just deleted both cores and re applied them, both work for me, so I'm not sure why they won't for you , did you try yesterdays Hallmeier release.? sorry I couldn't help more.

https://github.com/hallmeier/openfgpa-GBC

**Comment by DunhamGitHub** [comment]
> I just deleted both cores and re applied them, both work for me, so I'm not sure why they won't for you , did you try yesterdays Hallmeier release.? sorry I couldn't help more.
> 
> https://github.com/hallmeier/openfgpa-GBC

I have not tried the "Hallmeier" release.

I will try to a) delete both cores 1.0.8, b) start the Pocket, c) reinsert the Cores and try again

**Comment by DunhamGitHub** [comment]
Installed 1.0.6, FF worked perfectly. 1.0.8 does not work!

**Comment by Dawbo66** [comment]
Ok sorry I couldn't be more help. 👍

**Comment by budude2** [comment]
> Installed 1.0.6, FF worked perfectly. 1.0.8 does not work!

Did you verify it is enabled in the core settings? It seems to be off by default for some strange reason
