### ISSUE TITLE
Can we create a GBA FPGA core using a Real-Time Clock

### ISSUE THREAD

**Issue by ouni666** [budude2/openfpga-GBC#50]
Can we create a GBA FPGA core using a Real-Time Clock

**Comment by GoldZabu** [comment]
Go ahead if you want to. I’d recommend using the MiSTer GBA core as a starting point since it’s open source. I think it’s really great that you’ve decided to take this on for the community. Now maybe Budude2 can take a well deserved break and have people quit bothering him about a GBA core.

**Comment by reminon** [comment]
The dev is working hard on completing this core. I'm sure he will get to if if it interests him.

**Comment by budude2** [comment]
Unrelated to this core, but I am working on it
