### ISSUE TITLE
Proposal: Implement Rewind Feature ⏪

### ISSUE THREAD

**Issue by huuug** [budude2/openfpga-GBC#53]
This proposal suggests the introduction of a rewind capability in the GB/GBC core of the Analogue Pocket, similar to the existing functionality in the MiSTer FPGA project. This feature would permit users to rewind several seconds of gameplay, which is beneficial for navigating difficult sections or correcting mistakes.

**Comment by Bris4e** [comment]
Maybe on todo list, hope the feature will be achieved

**Comment by budude2** [comment]
This probably won't be possible on the pocket, at least not without a lot of work and investigation
