### ISSUE TITLE
Feature request: Disable (unmap) fast forward option completely

### ISSUE THREAD

**Issue by hak33m16** [budude2/openfpga-GBC#57]
Right now it's very easy to accidentally tap the fast forward button, and this is kind of annoying. I don't want to remap it I just want to unmap it

**Comment by Dawbo66** [comment]
I thought there was an option to turn it on/ off ? In the core settings.

**Comment by hak33m16** [comment]
@Dawbo66 Could you point me to where? I only see an option to remap it

**Comment by Dawbo66** [comment]
Yes in the settings it says " enable rumble"

**Comment by hak33m16** [comment]
Ah I see, it was at the top level, and not next to the fast forward options itself. Also was looking for fast forward and not "FF", I didn't realize that's what that meant. Thank you

**Comment by Dawbo66** [comment]
Glad its sorted..
