### ISSUE TITLE
gb_bios.bin file 

### ISSUE THREAD

**Issue by Smith-and-einstein** [budude2/openfpga-GBC#65]
hi, i can't find the files GB\GBC_bios.bin.
Thanks you for your support

**Comment by Dawbo66** [comment]
Use  Pupdate to update and they will automatically be downloaded.

**Comment by Smith-and-einstein** [comment]
alr thanks you

**Comment by Smith-and-einstein** [comment]
i just don't know how it's working for pupdate ....

**Comment by Smith-and-einstein** [comment]
i just did the update all and that's not working

**Comment by SaulGoodman1337** [comment]
could the error description be more precise? Nobody can help you like this

**Comment by Smith-and-einstein** [comment]
i just install the software "pupdate" for the bios files GBC\GB\GBA_bios.bin and that's not working after i used the "update all" on pupdate

**Comment by Smith-and-einstein** [comment]
it's alr i found that the install file of pupdate had to be in the cart sorry

**Comment by Smith-and-einstein** [comment]
yes ur right im a noob
