### ISSUE TITLE
Feature Request: Analogizer support

### ISSUE THREAD

**Issue by rinv** [budude2/openfpga-GBC#72]
Just picked up an Analogizer as a result of the eternally delayed DAC support for the Analogue Dock and would love to use your Game Boy Color core with it to play GBC games on a CRT 

https://github.com/RndMnkIII/Analogizer/wiki

**Comment by RndMnkIII** [comment]
Already done:
https://github.com/RndMnkIII/Analogizer_openfpga-GBC
